name: Build WebGPU Utilities

on:
  push:
    branches:
      - main

jobs:
  build:
    name: webgpu-utils Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Install playwright
        run: yarn playwright install --with-deps

      - name: Prettier
        run: yarn format:check

      - name: Build
        run: yarn run build

      - name: ESLint
        run: yarn lint

      - name: Test
        run: yarn test

      # ToDo: npm publish
